### ISSUE TITLE
Feature request: Font scaling

### ISSUE THREAD

**Issue by windowsrefund** [iurienistor/geonkick#39]
Just installed v1.8 from master. Thank you for this software!

Fonts are quite small on my end. Wondering if it would be possible to allow the user to bump them as needed. Going further, it appears that maximizing the UI has no effect as the usable space (controls, etc) is fixed. I guess I'm thinking the size of the window could/should result in everything being rendered in a way that made use of all the resulting space taken.

**Comment by iurienistor** [comment]
Hi! Thank you for the suggestion. I am sorry, but I have no plans to introduce dynamic layout. The fonts can be improved only by doing a redesign of PNG images which is not my strongest point. Also, there is a need to change many things in order to draw and modify in real time such dense graphs on bigger sizes but not affect drawing speed and GUI responsivity.
