### ISSUE TITLE
Add a master release time

### ISSUE THREAD

**Issue by unfa** [iurienistor/geonkick#48]
Right now Geonkick will immediately terminate previous note if you trigger a new one.

This is usually fine, but it may generate an ugly 'click' at times.

If there was a master Release time added, Geonkick could fade out the note instead of cutting it off immediately - even a very short release time of say 35 ms would prevent most clicks and thus produce a cleaner output.

**Comment by iurienistor** [comment]
The final output has a linear decay of 30ms if a new key is applied before the current percussion is played until the end.

But there there are two use cases that could anyway generate click:

* When a new key happens to be pressed in less than 30ms before the end of play.

* Sometimes filters or effects will add this click at the end because they are put after the general amplitude envelope. This can be fixed to move general envelope after filer and effects, but this will create some issues in the synthesis chain blocks, and there will be nedded more things to be added, input output limiter for filters and efects.

Thus, to fix these both, your sollution is the best. Thus I'll go with this. Thank you for this suggestion!

**Comment by iurienistor** [comment]
Implemented. This will fix the click due to last applied effects and when a new key happens to be pressed in less than 30ms before the end of play.
