### ISSUE TITLE
MIDI note to pitch

### ISSUE THREAD

**Issue by unfa** [iurienistor/geonkick#49]
Sometimes I wish I could enable pitch tracking in Geonkick so that it follows the pitch of the notes I play. This would allow it to be use as a bass synthesizer, producing some really nice 808s!

Also: I could use that to synthesize chimes or broken glass effects (thought it might need a polyphonic mode too).

I like that in ZynAddSubFX one can make the pitch tracking very delicate - it doesn't follow the 12-tone ET scale, but it's nice for special effects like chimes. So a knob for this could be great!

**Comment by iurienistor** [comment]
If you'll compile form [this branch](https://github.com/iurienistor/geonkick/tree/feat/pitch_shift), there is pitch shift in accordance with the node, relative to A4. The problem is that I'll need to use a better pitch shift algorithm, than the one that I have developed. It works well with downshift, but not very well which up-shift when especially working with more pure tones, But I'd don't think you'll see this problem for real percussion like kicks or snares... I am still thinking to merge this or not.

**Comment by unfa** [comment]
How about just using simplest speed control, like in any sampler? I guess you're implementing actual pitch shifting - that might not be necessary or even desired in many cases.

**Comment by iurienistor** [comment]
@unfa , By pitch shift I meant pitch shift by resampling, this is what I have implemented (also used by smaplers). Playing at a constant sample rate will change the pitch if resmapling the sample. But this also will change the duration of sound, which is ok for this case. The problem with resampling, especially, to increase the pitch (downsampling), there antialising is going on. The standard way is to apply a low pass filter, but I am afraid that this will take out also some useful frequencies.

**Comment by iurienistor** [comment]
@unfa I'll update the issue and schedule it for 1.9 version. I don't know if adding this too I'll fit into a resonable time for the elease of 1.9 version, but I'll do my best. Here on GitLab someone proposed this feature too https://gitlab.com/iurie/geonkick/issues/130
Thank you for suggestion. :)

**Comment by iurienistor** [comment]
Implemented. But it needs improvement for the future. Above A4 when tuned, may not work very well for some pure tones percussions.
